### ISSUE TITLE
glibc: C.UTF-8 not working?

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-core#24] opened 2016-03-14 01:39 UTC
Test suite:

``` sh
LC_ALL=C.UTF-8 sed -n '/^.$/p' <<< 有 # boom
LC_ALL=C.utf8 sed -n '/^.$/p' <<< 有 # boom, optional
LC_ALL=zh_CN.UTF-8 sed -n '/^.$/p' <<< 有
LC_ALL=C sed -n '/^.$/p' <<< 没
LC_ALL=POSIX sed -n '/^.$/p' <<< 没
```

**Comment by MingcongBai** [comment] 2016-03-14 01:42
Oops. Something had went wrong as it seems like...

```
root [ locale ] # localedef -i C -c -f UTF-8 -A /usr/share/locale/locale.alias C.UTF-8 
No definition for LC_NUMERIC category found
No definition for LC_MONETARY category found
No definition for LC_MESSAGES category found
No definition for LC_PAPER category found
No definition for LC_NAME category found
No definition for LC_ADDRESS category found
No definition for LC_TELEPHONE category found
No definition for LC_MEASUREMENT category found
```

**Comment by MingcongBai** [comment] 2016-03-14 01:42
But yes the file is installed as `/usr/share/i18n/locales/C`.

**Comment by MingcongBai** [comment] 2016-03-14 01:43
While the "test suite" returned all `0`... This is weird.

**Comment by Artoria2e5** [comment] 2016-03-14 01:43
Uh, you are supposed to look at if 有 are really printed..

**Comment by MingcongBai** [comment] 2016-03-14 01:44
```
root [ locale ] # LC_ALL=C.UTF-8 sed -n '/^.$/p' <<< 有 # boom
有
root [ locale ] # LC_ALL=C.utf8 sed -n '/^.$/p' <<< 有 # boom, optional
有
root [ locale ] # LC_ALL=zh_CN.UTF-8 sed -n '/^.$/p' <<< 有
有
root [ locale ] # LC_ALL=C sed -n '/^.$/p' <<< 没
root [ locale ] # LC_ALL=POSIX sed -n '/^.$/p' <<< 没
```

As predicted.

**Comment by Artoria2e5** [comment] 2016-03-14 01:45
Weird, it didn't work on your 0.81 when I tested it..

**Comment by MingcongBai** [comment] 2016-03-14 01:45
> Weird, it didn't work on your 0.81 when I tested it..

0.81?

**Comment by Artoria2e5** [comment] 2016-03-14 01:45
By the way, add newlines after the opening and before the closing ```.

**Comment by Artoria2e5** [comment] 2016-03-14 01:45
@MingcongBai Your ssh-then-ssh-machine.

**Comment by MingcongBai** [comment] 2016-03-14 01:47
> @MingcongBai Your ssh-then-ssh-machine.

Gotcha, but it seemed to work. But locale-gen would not like this file as it seemed like...

**Comment by Artoria2e5** [comment] 2016-03-14 01:48
So perhaps it's because we didn't include the locale in the archive? Gosh this is supposed to be always there…

**Comment by Artoria2e5** [comment] 2016-03-14 01:49
By the way I guess 'no definition' is the right situation (if it returns 0)

**Comment by MingcongBai** [comment] 2016-03-14 01:50
> By the way I guess 'no definition' is the right situation (if it returns 0)

The problem is that it returned a `1`.

**Comment by MingcongBai** [comment] 2016-03-14 01:50
> So perhaps it's because we didn't include the locale in the archive? Gosh this is supposed to be always there…

Not the case for Debian either though...

**Comment by Artoria2e5** [comment] 2016-03-14 01:52
On my Ubuntu Xenial (16.04), `sed` got `C.UTF-8` but not `C.utf8`.

Only these two seem to be in `supported/local`:

```
en_US ISO-8859-1
en_US.UTF-8 UTF-8
```

`supported/en` is just a bunch of other `en` locales.

**Comment by MingcongBai** [comment] 2016-04-27 17:08
Included Fedora patch instead, which is actually compatible with our `glibc` configuration (Debian 2.23 is still in exp and the data wouldn't work).

With the Fedora patch, `localedef` works without an error. I will close this when I complete the old test suite as shown above.

**Comment by MingcongBai** [comment] 2016-04-27 17:10
``` bash
root [ / ] # locale -a | grep C
bo_CN
bo_CN.utf8
C
cs_CZ
cs_CZ.iso88592
cs_CZ.utf8
C.utf8
```

A digested output sample.

**Comment by MingcongBai** [comment] 2016-04-27 17:11
```
root [ / ] # LC_ALL=C.UTF-8 sed -n '/^.$/p' <<< 有 # boom
有
root [ / ] # LC_ALL=C.utf8 sed -n '/^.$/p' <<< 有 # boom, optional
有
root [ / ] # LC_ALL=zh_CN.UTF-8 sed -n '/^.$/p' <<< 有
有
root [ / ] # LC_ALL=C sed -n '/^.$/p' <<< 没
root [ / ] # LC_ALL=POSIX sed -n '/^.$/p' <<< 没
```

Good.

**Closed as completed** 2016-04-27 17:12 UTC
