### ISSUE TITLE
RFC: test Kernel 4.9 &  BBR in 4.1.99; consider defaulting BBR

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aosc-os-core#44] opened 2016-12-06 21:26 UTC
There are quite some favorable reports on performance improvements ("better than finalspeed") from BBR ([paper](https://queue.acm.org/detail.cfm?ref=rss&id=3022184)) on Chinese [read: shitty] network conditions, and BBR appears optimized for wireless connections as well. Perhaps most users will find it useful.

Note: Defaulting to BBR would make `fq qdisc` an integral part of AOSC OS.

**Comment by MingcongBai** [comment] 2016-12-06 22:11
#TODO Move to https://github.com/AOSC-Dev/aosc-os-abbs.

**Comment by biergaizi** [comment] 2016-12-12 14:32
It is incorrect to understand that BBR is designed for shitty network conditions, in contrary, it was designed to save the general public Internet. The modern Internet is largely destroyed by BufferBloat, that's the reason a simple BitTorrent can break your entire network, even if enough bandwidth is available for web browsing. 

`fq_codel` was designed to mitigate the effect of BufferBloat, but it has to be deployed in the bottleneck of the network and requires some tweaks which is not practice in institutional network. BBR is our first powerful weapon to solve all those problems of BufferBloat in almost all circumstance.

**Comment by biergaizi** [comment] 2016-12-12 14:32
It is incorrect to understand that BBR is designed for shitty network conditions, in contrary, it was designed to save the general public Internet. The modern Internet is largely destroyed by BufferBloat, that's the reason a simple BitTorrent can break your entire network, even if enough bandwidth is available for web browsing. 

`fq_codel` was designed to mitigate the effect of BufferBloat, but it has to be deployed in the bottleneck of the network and requires some tweaks which is not practice in institutional network. BBR is our first powerful weapon to solve all those problems of BufferBloat in almost all circumstance.

**Comment by biergaizi** [comment] 2016-12-12 14:32
It is incorrect to understand that BBR is designed for shitty network conditions, in contrary, it was designed to save the general public Internet. The modern Internet is largely destroyed by BufferBloat, that's the reason a simple BitTorrent can break your entire network, even if enough bandwidth is available for web browsing. 

`fq_codel` was designed to mitigate the effect of BufferBloat, but it has to be deployed in the bottleneck of the network and requires some tweaks which is not practice in institutional network. BBR is our first powerful weapon to solve all those problems of BufferBloat in almost all circumstance.

**Comment by biergaizi** [comment] 2016-12-12 14:32
It is incorrect to understand that BBR is designed for shitty network conditions, in contrary, it was designed to save the general public Internet. The modern Internet is largely destroyed by BufferBloat, that's the reason a simple BitTorrent can break your entire network, even if enough bandwidth is available for web browsing. 

`fq_codel` was designed to mitigate the effect of BufferBloat, but it has to be deployed in the bottleneck of the network and requires some tweaks which is not practice in institutional network. BBR is our first powerful weapon to solve all those problems of BufferBloat in almost all circumstance.

**Comment by biergaizi** [comment] 2016-12-12 14:32
It is incorrect to understand that BBR is designed for shitty network conditions, in contrary, it was designed to save the general public Internet. The modern Internet is largely destroyed by BufferBloat, that's the reason a simple BitTorrent can break your entire network, even if enough bandwidth is available for web browsing. 

`fq_codel` was designed to mitigate the effect of BufferBloat, but it has to be deployed in the bottleneck of the network and requires some tweaks which is not practice in institutional network. BBR is our first powerful weapon to solve all those problems of BufferBloat in almost all circumstance.

**Comment by biergaizi** [comment] 2016-12-12 14:32
It is incorrect to understand that BBR is designed for shitty network conditions, in contrary, it was designed to save the general public Internet. The modern Internet is largely destroyed by BufferBloat, that's the reason a simple BitTorrent can break your entire network, even if enough bandwidth is available for web browsing. 

`fq_codel` was designed to mitigate the effect of BufferBloat, but it has to be deployed in the bottleneck of the network and requires some tweaks which is not practice in institutional network. BBR is our first powerful weapon to solve all those problems of BufferBloat in almost all circumstance.

**Comment by MingcongBai** [comment] 2016-12-12 14:39
@biergaizi Woah that is a lot of duplicate posts. Would you mind of I remove the dips?

**Comment by Artoria2e5** [comment] 2016-12-12 18:30
@biergaizi I am not saying BBR is designed for shitty connections. What I am saying is since BBR does not compromise goodput as terribly as CUBIC under packet loss, it should work better when kraken kicks in (and people are confirming that with Chinese network.)

**Comment by MingcongBai** [comment] 2016-12-12 21:11
Also on the note of the title... Kernel is a part of the ABBS tree but not the Core... So there really isn't a version target for this issue.

**Comment by MingcongBai** [comment] 2016-12-12 21:12
With that said, I will close this issue after the kernel update is merged to master, listing all commits in ABBS tree as references.

**Closed as completed** 2016-12-23 16:23 UTC
